### ISSUE TITLE
Error CS0066 in IPlayFabSignalR.cs

### ISSUE THREAD

**Issue by cannoness** [PlayFab/UnitySDK#202] opened 2018-08-10 02:00 UTC
Assets/PlayFabSdk/Shared/Internal/PlayFabSignalR/IPlayFabSignalR.cs(9,22): error CS0066: `PlayFab.Internal.IPlayFabSignalR.OnDisconnected': event must be of a delegate type

Lines 8 and 9.

        event Action OnReconnected;
        event Action OnDisconnected;

Running Unity update 2018.2.2f1 with Visual Studio 15.7.5

**Comment by pgilmorepf** [comment] 2018-09-04 20:29
Thanks for reporting this, we will investigate.

**Comment by pgilmorepf** [comment] 2018-09-05 21:00
I am unable to reproduce this issue with:
Unity 2018.2.5f1 and Visual Studio 15.7.6
Given that our environments are not different in any relevant way, I suspect that's not the issue.

I suspect that your project has another class called "Action" in the global scope of your project (without a namespace), and that has caused an unexpected conflict with our SDK.
I highly suggest that developers do not create name-conflicts with the System libraries, as this will create conflicts with most 3rd party SDKs, not just ours.

It's also possible that another 3rd party library that you may be using has conflicted with ours, via the same name conflict method described above. In that case, you'd have to file that bug with the other 3rd party plugin.

To confirm the issue, select "Action" from that code, right click, and "go to definition".
If it takes you to the definition of the C# core System.Action, then ... the problem is something else and you should tell us.
If it takes you someplace else, then the name conflict as described above is confirmed.

I am going to close this issue, because I cannot repo the issue, and we have confirmed many very similar issues in the past. Let us know if you are unable to resolve the problem.

**Closed by pgilmorepf** 2018-09-05 21:00 UTC
