### ISSUE TITLE
SingletonMonobehaviour implementation is not thread safe

### ISSUE THREAD

**Issue by zac-playfab** [PlayFab/UnitySDK#42] opened 2015-09-23 17:50 UTC
Need to update the SingletonMonobehaviour.cs class to be thread safe. 

More details reported here:
https://support.playfab.com/helpdesk/tickets/548

**Comment by JohnTube** [comment] 2015-10-07 23:06
maybe this could help:
```csharp
using UnityEngine;

public class Singleton<T> : MonoBehaviour where T : MonoBehaviour {

    //the variable is declared to be volatile to ensure that
    //assignment to the instance variable completes before the
    //instance variable can be accessed.
    private static volatile T instance;

    private static object _lock = new object();

    public static T Instance {
        get {
            if (ApplicationIsQuitting) {
                Debug.LogWarning(string.Format("[Singleton] Instance '{0}' already destroyed on application quit. Won't create again - returning null.", typeof(T)));
                return null;
            }
            lock (_lock) {
                if (instance == null) {
                    Object[] objects = FindObjectsOfType(typeof(T));
                    if (objects == null || objects.Length < 1) {
                        GameObject singleton = new GameObject();
                        instance = singleton.AddComponent<T>();
                        singleton.name = string.Format("(singleton) {0}" + typeof(T));
                        DontDestroyOnLoad(singleton);
                        Debug.LogWarning(string.Format("[Singleton] An Instance of {0} is needed in the scene, so '{1}' was created with DontDestroyOnLoad.", typeof(T), singleton.name));
                    }
                    else if (objects.Length >= 1) {
                        instance = objects[0] as T;
                        if (objects.Length > 1) {
                            Debug.LogWarning("[Singleton] Something went really wrong - there should never be more than 1 singleton! Reopening the scene might fix it.");
                        }
                        return instance;
                    }
                }
                return instance;
            }
        }
    }

    public static bool ApplicationIsQuitting;

    public void OnDestroy() {
        ApplicationIsQuitting = true;
    }
}
```

I'm open to discussion whether:
- it is good to [also] assign `instance` in `Awake()` or `OnEnable()` or `Start()` other than in `Instance`'s getter.
- replace `where T : MonoBehaviour` with `where T : Singleton<T>`

You can of course add back the initialization logic from original if needed.

**Comment by pgilmorepf** [comment] 2015-11-13 00:21
This is by design.
Closing the issue.

**Closed by pgilmorepf** 2015-11-13 00:21 UTC
