### ISSUE TITLE
PlayfabAdminModels contain enum for Regions but no conversion to String Version

### ISSUE THREAD

**Issue by MScottAdams** [PlayFab/UnitySDK#230] opened 2020-04-27 20:12 UTC
Originally reported: https://github.com/PlayFab/gsdk/issues/51

The PlayFabAdminModels.cs has a region enum (see below) but GameManager and the Client/Server Api all require strings instead of enum. To further confuse things the strings in those api(s) are listed differently "EastUs" instead of USEast.  Please provide a conversion routine from enum to string and string to enum so the different APIs can be consistent.

    public enum Region
    {
        USCentral,
        USEast,
        EUWest,
        Singapore,
        Japan,
        Brazil,
        Australia
    }

**Comment by pgilmorepf** [comment] 2020-05-07 17:56
For your specific request:
Region.ToString() and Enum.Parse(...) should perform the string conversions you require.

I caution against relying on this, as some of our server APIs can be ahead of older SDK releases, and regions can be returned that may not exist in your enum. This is the specific purpose of the string region fields, to make it possible for your client to handle regions that don't exist at the time of publish. MS Azure and PlayFab are actively adding regions, and we've seen multiple new regions light up in the last year.

I'm going to close this bug as by design.

**Closed by pgilmorepf** 2020-05-07 17:56 UTC
